spring:
  application:
    name: register
eureka:
  instance:
    hostname: localhost
  client:
    # 当前服务是否注册到注册中心
    register-with-eureka: true
    # true 启动 抛出异常 com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
    fetch-registry: true
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:4000/eureka/
  server:
    #  是否开启注册中心自我保护、开发环境可以关闭、生成环境打开
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
server:
  port: 3000